---
title: "R Notebook"
output: html_notebook
---

```{general_characteristics}

library(tidyverse)

#importing dataset as data frames and naming columns

cysteine_count <- read_tsv("maxq_cysteine_count.tsv", col_names = FALSE)
names(cysteine_count) <- c("ID", "Cysteine count")

seq_length <- read_tsv("maxq_seq_len.tsv", col_names = FALSE)
names(seq_length) <- c("ID", "Sequence length")

signalp <- read_tsv("sigp.tsv", col_names = FALSE)
names(signalp) <- c("ID", "SignalP")

mwpi <- read_tsv("max_mw_pi.tsv", col_names = FALSE)
names(mwpi) <- c("ID", "Molecular weight (DA)","Isoelectric point")
```


```{join_general_char_datafr}

join_char <- left_join(seq_length, cysteine_count, by = "ID")

join_char2 <- left_join(join_char, signalp, by="ID")

join_char3 <- left_join(join_char2, mwpi, by="ID")


```

```{blast_filtering_function}

read_blast <- function(file_name, columns = c(1,2,5,12)){
 # place this behind the column argument to serve as "default if no other columns are given: c(1,2,5,12) 
  blast_result <- read_delim(file_name,delim = "\t",col_names = FALSE)
  blast_result <- blast_result[,columns]
  names(blast_result) <- c("ID", "Hit_ID", "Evalue", "Description")
  blast_result <- filter(blast_result, Evalue < 1e-5)
    # There is sometimes more than one blast hit per protein so we need to pick the best E value for each
  blast_result <- blast_result %>% group_by(Hit_ID) %>% top_n(1,1/Evalue)
  
  # read the file
  # select the columns
  # filter out bad blast hits

  blast_result
}
```

```{using_function_for_blast_databases}

blast_arachno <- read_blast("max_arachnoserver_blastp.tsv")

blast_uniprot <- read_blast("max_uniprot_blast.tsv", c(1,2,5,13))

blast_swissprot <- read_blast("max_swissprot_blastp.tsv")

blast_nr <- read_blast("max_nr.blastp")
```

```{join_char_table_to_blast_dataframes}

joined_data <- left_join(join_char3, blast_arachno, by = c("ID"="ID"))

joined_data2 <- left_join(joined_data,blast_uniprot, by = c("ID"="ID"), suffix = c(".arachnoserver",".uniprot_toxins"))

joined_data3 <- left_join(joined_data2,blast_swissprot, by = c("ID"="ID")) 

joined_data4 <- left_join(joined_data3,blast_nr, by = c("ID"="ID") , suffix = c(".swissprot",".nr"))
```

```{write_data_to_file}

write_delim(joined_data4,"maxquant_protein_table.tsv",delim = "\t")
  
```

```{r}

library(tidyverse)

maxquant_protein_table2 <- read_tsv("maxquant_protein_table.tsv", col_names = TRUE)

#remove the cysteine count column
maxquant_protein_table2$"Cysteine count" <- NULL

#import cysteine data
cysteine_count_per_30aa <- read_tsv("maquant_cys_dens_def.tsv", col_names = FALSE)
names(cysteine_count_per_30aa) <- c("ID", "max_cysteine_count", "knot_found")

#join two dataframes together

maxquant_protein_table_with_c <- left_join(maxquant_protein_table2, cysteine_count_per_30aa, by = "ID")


```


```{r}

#neaten table

#test for duplicates (found 202 duplicate rows - why? )
maxquant_protein_table_with_c[duplicated(maxquant_protein_table_with_c), ]

#obtain only the unique rows (i.e without duplicates!)
unique_protein_table <- unique(maxquant_protein_table_with_c)

#get a list of the column names 
colnames(unique_protein_table)

#reorder columns so cysteine information is next to other protein characteristics

reordered_unique_protein_table <- unique_protein_table[c(1,2,3,18,19,4:17)]

#convert molecular weight from DA to kDA and rename column

reordered_unique_protein_table$`Molecular weight (DA)` <- reordered_unique_protein_table$`Molecular weight (DA)`/1000

names(reordered_unique_protein_table)[6] <- "Molecular_weight(kDA)"

#decrease decimals for numeric columns

reordered_unique_protein_table$`Molecular_weight(kDA)` <- round(reordered_unique_protein_table$`Molecular_weight(kDA)`, digits =2)

reordered_unique_protein_table$`Isoelectric point` <- round(reordered_unique_protein_table$`Isoelectric point`, digits =2)

#rename Sequence length to contain no spaces

names(reordered_unique_protein_table)[2] <- "Sequence_length"

```

```{r}
#refining the table to obtain a smaller subset with likely toxin candidates


#change NA values to "UN" for unknown
reordered_unique_protein_table$SignalP[is.na(reordered_unique_protein_table$SignalP)] <- "UN"

#select the characters Y and UN from the SignalP column (use %in% if it is the same column or | (=or) if it is in a different column)

signals_only <- reordered_unique_protein_table %>% filter(SignalP %in% c("Y", "UN"))

#now select rows from the signals_only dataframe that are equal or greater than 6 in cysteine density

high_cysteines <- filter(signals_only, max_cysteine_count >= 6)

#find proteins shorter than 150aa

short <- filter(high_cysteines, Sequence_length <150)
```


```{r}
write_delim(reordered_unique_protein_table,"maxquant_protein_table_updated.tsv",delim = "\t")

write_delim(high_cysteines, "Toxin_chars_table.tsv", delim= "\t")

write_delim(short, "Toxin_chars_short_table.tsv", delim = "\t")
```

